name: CI/CD - Backend Clinic System

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout del código
           uses: actions/checkout@v3

         - name: Setup de Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '18'

         - name: Instalación de dependencias
           run: npm install

         - name: Correr tests
           run: npm test || echo "No hay tests definidos aún"

         - name: Login a Docker Hub
           run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

         - name: Build de imagen Docker
           run: docker build -t ${{ secrets.DOCKER_USERNAME }}/clinic-system-backend .

         - name: Push de imagen Docker
           run: docker push ${{ secrets.DOCKER_USERNAME }}/clinic-system-backend
